### PR TITLE
Token calculator in account

### LINKED ISSUE #384: Create Calculator results card component

### LINKED ISSUE #385: Add a token calculator page based on the Figma design

### PR DESCRIPTION
**Pull request by marc-aurele-besner**
## Token calculator in account

- Add Tabs in the Account Rewards box with Previous rewards earn
close #384 
close #385 

## Note

- Missing gemini-3f data
- Missing to calculate final mainnet %

### Screenshot

PreviousRewards
CurrentRewards

### CODE REVIEW

**Review by natachadelarosa — CHANGES_REQUESTED** [review]
1- Can we present the numbers with just two decimal places
2- Let's change the last column name with some abbreviation and add a tooltip with the complete name, the tooltip can be added using a ? icon at the end of the column name, please validate this with Diana:

image

**Comment by marc-aurele-besner** [comment]
Sorry for the delay @natachadelarosa 

I addressed your comments, that been said I'm left with the note I had In the PR

- Not sure if I can still query gemini 3f subsquid to get these rewards...
- Not sure how each of these network reward translate to mainnet rewards and %...

**Review by natachadelarosa — COMMENTED** [review]
Looks good to me, on the account list I sow this, can it be solved before merging?

image

**Review by natachadelarosa — APPROVED** [review]
Looks great! Thanks for the awesome work!

**Review by natachadelarosa — APPROVED** [review]
LGTM

**Pull request merged**
