### PR TITLE
Create a switch in staking section to switch between indexed data and rpc data

### PR DESCRIPTION
**Pull request by marc-aurele-besner**
## Create a switch in the staking section to switch between indexed data and RPC data

- Create a switch on the operator list and manage my operator to switch between indexed data and RPC data
- Query a lot of chain data (a lot more than currently consumed)
- Replace the data with the RPC data and remove the nominator tabs since we don't have it

### Screenshots

image

___

### **PR Type**
Enhancement, Bug fix, Error handling

___

### **Description**
- Added a switch component to toggle between indexed data and RPC data in the Operator Management and Operators List components.
- Integrated new state management for view states, allowing toggling between data sources.
- Updated operator data fetching logic to support RPC data, including necessary type definitions and error handling improvements.
- Created a reusable switch component for toggling states.
- Added logic to fetch and parse consensus data from RPC, updating state management to handle new data structures.
- Expanded state management to include new consensus data structures and methods to set various consensus-related states.
- Defined new TypeScript types for consensus data structures.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>OperatorManagement.tsx</strong><dd><code>Add switch for toggling data source in Operator Management</code></dd></summary>
<hr>

explorer/src/components/Operator/OperatorManagement.tsx

<li>Added a switch component to toggle between indexed data and RPC data.<br> <li> Integrated new state management for view states.<br> <li> Updated operator data fetching logic to support RPC data.<br> <li> Improved error handling and type definitions.<br>

</details>

  </td>
  <td><a href="https://github.com/subspace/astral/pull/730/files#diff-1728839c747fa9b636fe04951d7342836b3786430d6640d8bd9bd9ca72e9c8e3">+83/-28</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>OperatorsList.tsx</strong><dd><code>Add switch for toggling data source in Operators List</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

explorer/src/components/Operator/OperatorsList.tsx

<li>Added a switch component to toggle between indexed data and RPC data.<br> <li> Integrated new state management for view states.<br> <li> Updated operator data fetching logic to support RPC data.<br> <li> Improved error handling and type definitions.<br>

</details>

  </td>
  <td><a href="https://github.com/subspace/astral/pull/730/files#diff-2144a16cae24f1edb0774bfb0c1d2db81bf6100af1920189a1b1dbda4506bdaf">+113/-53</a></td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>Switch.tsx</strong><dd><code>Create reusable switch component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

explorer/src/components/common/Switch.tsx

- Created a new switch component for toggling states.

</details>

  </td>
  <td><a href="https://github.com/subspace/astral/pull/730/files#diff-840666dd4934e7603c288c7db41eb4cee4dbbfc2cfe96b90b5ab950224884d74">+30/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>useConsensusData.ts</strong><dd><code>Add consensus data fetching and parsing logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

explorer/src/hooks/useConsensusData.ts

<li>Added logic to fetch and parse consensus data from RPC.<br> <li> Updated state management to handle new data structures.<br> <li> Improved error handling.<br>

</details>

  </td>
  <td><a href="https://github.com/subspace/astral/pull/730/files#diff-734fc7f643a5c569f33bad078492efc35cb5f716856b646e59a933a1f322c886">+159/-6</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>consensus.ts</strong><dd><code>Expand consensus state management</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

explorer/src/states/consensus.ts

<li>Expanded state management to include new consensus data structures.<br> <li> Added methods to set various consensus-related states.<br>

</details>

  </td>
  <td><a href="https://github.com/subspace/astral/pull/730/files#diff-65292cb11b941bb083c14ec6116aae44a5b6525f0a35166a59698cd1e21d77a1">+91/-5</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>view.ts</strong><dd><code>Add view state management with RPC data toggle</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

explorer/src/states/view.ts

<li>Added new state management for view states.<br> <li> Included a toggle for using RPC data.<br>

</details>

  </td>
  <td><a href="https://github.com/subspace/astral/pull/730/files#diff-5365bc92bb38e535090ab99368f4aaf5ad43cd459db3e71e4a1bbda4e49b35e0">+30/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>consensus.ts</strong><dd><code>Define TypeScript types for consensus data</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

explorer/src/types/consensus.ts

- Defined new TypeScript types for consensus data structures.

</details>

  </td>
  <td><a href="https://github.com/subspace/astral/pull/730/files#diff-e50d0c017ad68aed1dfe87e953f345c1d30af5efaf9ed0f2246e6b5feafcb88b">+112/-0</a>&nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by jfrank-summit** [comment]
Initial thoughts/questions after reviewing the preview, not the code:

The toggle isn't clear to me immediately which is Indexed Data and which is RPC and why one is represented as "on" and the other "off". I think this should be more explicit and/or intuitive and possibly with a hover explanation.
Is there a way to properly represent Status while in RPC mode? For example, an operator I have fully withdrawn from already still shows "Deregistered, funds ready to unlock".
No data is showing up for Indexed Data.

**Comment by marc-aurele-besner** [comment]
> Initial thoughts/questions after reviewing the preview, not the code:
> 
> The toggle isn't clear to me immediately which is Indexed Data and which is RPC and why one is represented as "on" and the other "off". I think this should be more explicit and/or intuitive and possibly with a hover explanation. Is there a way to properly represent Status while in RPC mode? For example, an operator I have fully withdrawn from already still shows "Deregistered, funds ready to unlock". No data is showing up for Indexed Data.

I'll work on an other solution for the visual control.

for the status, the chain only return the status, the squid was added to the status in our db, when it will be unlocked.
I need to see if I can reproduce this data from rpc

**Comment by marc-aurele-besner** [comment]
@jfrank-summit something like this? 
Screenshot 2024-07-15 at 7 17 39 AM
Screenshot 2024-07-15 at 7 17 47 AM

**Comment by marc-aurele-besner** [comment]
@jfrank-summit as discussed
Live Data
Archived Data

**Review by jfrank-summit — APPROVED** [review]

**Pull request merged**
